CREATE TABLE `AdmPractice` (
  `Identificator` char(150) DEFAULT NULL COMMENT 'Идентификатор',
  `EventAdmPractice` varchar(200) DEFAULT NULL COMMENT 'Событие делопроизводства',
  `RegNumber` varchar(200) NOT NULL COMMENT 'Уникальный номер АП',
  `RegionMaterial` char(150) DEFAULT NULL COMMENT 'Регион определения',
  `MaterialNum` varchar(200) DEFAULT NULL COMMENT 'Серия и номер определения',
  `Declarer` varchar(200) DEFAULT NULL COMMENT 'Заявитель',
  `RulingUnit` varchar(200) DEFAULT NULL COMMENT 'Подразделение, вынесшее определение',
  `ProtocolNum` varchar(200) DEFAULT NULL COMMENT 'Серия и номер первичного материала',
  `Region` char(200) DEFAULT NULL COMMENT 'Регион нарушения',
  `NarushPlace` varchar(250) DEFAULT NULL COMMENT 'Адрес нарушения',
  `Department` varchar(200) DEFAULT NULL COMMENT 'Подразделение, выявившее нарушение',
  `Inspector` varchar(200) DEFAULT NULL COMMENT 'Должностное лицо, выявившее нарушение',
  `KoAP` varchar(200) DEFAULT NULL COMMENT 'Вид нарушения',
  `Subject` char(200) DEFAULT NULL COMMENT 'Субъект правонарушения',
  `OffenderCategory` char(200) DEFAULT NULL COMMENT 'Категория нарушителя',
  `Offender` char(200) DEFAULT NULL COMMENT 'Нарушитель',
  `Birthday` date DEFAULT NULL COMMENT 'Дата рождения /регистрации нарушителя',
  `Address` varchar(200) DEFAULT NULL COMMENT 'Адрес регистрации нарушителя',
  `INN` varchar(25) DEFAULT NULL COMMENT 'ИНН/КПП нарушителя',
  `OGRN` varchar(25) DEFAULT NULL COMMENT 'ОГРН нарушителя',
  `GRZ` varchar(15) DEFAULT NULL COMMENT 'Регистрационный знак ТС',
  `TSModel` varchar(50) DEFAULT NULL COMMENT 'Модель',
  `VIN` varchar(25) DEFAULT NULL COMMENT 'VIN',
  `Color` varchar(25) DEFAULT NULL COMMENT 'Цвет',
  `Owner` varchar(50) DEFAULT NULL COMMENT 'Владелец',
  `DecisionNum` varchar(50) DEFAULT NULL COMMENT 'Серия и номер постановления',
  `DecisionWhoMade` varchar(200) DEFAULT NULL COMMENT 'Кем вынесено',
  `DecisionRegion` varchar(200) DEFAULT NULL COMMENT 'Регион вынесения постановления',
  `DecisionDepartment` varchar(200) DEFAULT NULL COMMENT 'Подразделение, вынесшее постановление',
  `JudicialSector` varchar(200) DEFAULT NULL COMMENT 'Судебный участок',
  `PanishmentType` char(25) DEFAULT NULL COMMENT 'Вид наказания',
  `PenaltySize` decimal(12,2) DEFAULT NULL COMMENT 'Сумма штрафа',
  `PenaltyPeriod` int(8) DEFAULT NULL COMMENT 'Срок лишения',
  `ArrestPeriod` int(8) DEFAULT NULL COMMENT 'Срок ареста',
  `DisqualificationPeriod` int(8) DEFAULT NULL COMMENT 'Срок дисквалификации',
  `CompulsoryWorkPeriod` int(8) DEFAULT NULL COMMENT 'Срок обязательных работ',
  `Payment` int(20) DEFAULT NULL COMMENT 'Сумма оплаты',
  `Residue` int(20) DEFAULT NULL COMMENT 'Осталось оплатить',
  `RegionFSSP` varchar(200) DEFAULT NULL COMMENT 'Регион, куда отправлено в ФССП',
  `DepartureDateFSSP` date DEFAULT NULL COMMENT 'Дата отправки в ФССП',
  `DepartmentFSSP` varchar(200) DEFAULT NULL COMMENT 'Подразделение ФССП',
  `DateLastCardView` date DEFAULT NULL COMMENT 'Дата, время последнего просмотра карточки',
  `DateNarush` date DEFAULT NULL COMMENT 'Дата и время нарушения',
  `DateSearchCheck` date DEFAULT NULL COMMENT 'Дата, время проверки на розыск нарушителя ',
  `Result` varchar(50) DEFAULT NULL COMMENT 'Результат проверки на розыск нарушителя',
  `DateSearchCheckTS` date DEFAULT NULL COMMENT 'Дата, время проверки на розыск ТС и документов',
  `ResultCheckTS` varchar(50) DEFAULT NULL COMMENT 'Результат проверки на розыск транспортного средства',
  `Violation` varchar(200) DEFAULT NULL COMMENT 'Нарушение',
  `Marka` varchar(100) DEFAULT NULL COMMENT 'Марка',
  `WULost` varchar(100) DEFAULT NULL COMMENT 'ВУ утеряно',
  `PerformanceStatus` varchar(200) DEFAULT NULL COMMENT 'Состояние исполнения',
  `DirectionMaterials` varchar(200) DEFAULT NULL COMMENT 'Направление материалов - серия и номер (тип)',
  `ReceiptMaterials` varchar(200) DEFAULT NULL COMMENT 'Получение материалов - серия и номер (тип)',
  `PostUserDepartment` varchar(200) DEFAULT NULL COMMENT 'Должностное лицо, составившее первичный материал',
  `EffectiveDate` date DEFAULT NULL COMMENT 'Дата вступления в ЗС',
  `Citizenship` char(25) DEFAULT NULL COMMENT 'Гражданство',
  `OwnerCategory` char(25) DEFAULT NULL COMMENT 'Категория владельца ТС',
  `Tinting` char(25) DEFAULT NULL COMMENT 'Требования по тонировке',
  `TSCategory` char(25) DEFAULT NULL COMMENT 'Категория ТС',
  `PrimaryMaterialDate` date DEFAULT NULL COMMENT 'Дата составления  первичного материала',
  `PlaceWork` varchar(100) DEFAULT NULL COMMENT 'Место работы',
  `AdditionalInformation` varchar(250) DEFAULT NULL COMMENT 'Дополнительная информация',
  `ResultCheckGRZ` varchar(50) DEFAULT NULL COMMENT 'Результат проверки на розыск номерного знака',
  `ResultCheckWU` varchar(50) DEFAULT NULL COMMENT 'Результат проверки на розыск водительского удостоверения',
  `ResultCheckSTS` varchar(50) DEFAULT NULL COMMENT 'Результат проверки на розыск свидетельства о регистрации',
  `Phone` char(10) DEFAULT NULL COMMENT 'Телефон нарушителя',
  `NumberWU` char(20) DEFAULT NULL COMMENT 'Номер ВУ (ДУЛ) нарушителя',
  `DataWU` date DEFAULT NULL COMMENT 'Дата выдачи ВУ (ДУЛ) нарушителя',
  `KindIntoxication` varchar(100) DEFAULT NULL COMMENT 'Вид опьянения',
  `TypeMaterial` varchar(100) DEFAULT NULL COMMENT 'Вид материала',
  `FactualInformation` varchar(150) DEFAULT NULL COMMENT 'Фактические сведения',
  `GPSLat` varchar(8) DEFAULT NULL COMMENT 'Широта',
  `GPSLong` varchar(9) DEFAULT NULL COMMENT 'Долгота',
  `BasisTerminationProduction` varchar(150) DEFAULT NULL COMMENT 'Основание прекращения производства',
  `ReasonTerminationProduction` varchar(150) DEFAULT NULL COMMENT 'Причина прекращения производства',
  `RegionWithdrawalWU` varchar(100) DEFAULT NULL COMMENT 'Регион изъятия ВУ',
  `DepartmentWithdrawalWU` varchar(100) DEFAULT NULL COMMENT 'Подразделение изъятия ВУ',
  `AccidentParticipant` varchar(100) DEFAULT NULL COMMENT 'Участник ДТП',
  `BeginnngTerm` date DEFAULT NULL COMMENT 'Начало срока лишения',
  `Postponement` char(10) DEFAULT NULL COMMENT 'Отсрочка оплаты штрафа',
  `DocumentNum` char(25) DEFAULT NULL COMMENT 'Серия и номер документа — основания',
  `MailID` char(20) DEFAULT NULL COMMENT 'Почтовый идентификатор',
  `InternationalRoadTransport` varchar(50) DEFAULT NULL COMMENT 'Международная автомобильная перевозка',
  `MaterialDate` date DEFAULT NULL COMMENT 'Дата  определения',
  `RecordCreationDate` date DEFAULT NULL COMMENT 'Дата  и время создания  записи',
  `DecisionDate` date DEFAULT NULL COMMENT 'Дата вынесения   постановления',
  `ReviewDate` date DEFAULT NULL COMMENT 'Дата рассмотрения',
  `RegionViolation` varchar(100) DEFAULT NULL COMMENT 'Регион нарушения',
  `TypeAccounting` varchar(100) DEFAULT NULL COMMENT 'Вид учета',
  `Unknown1` varchar(200) DEFAULT NULL,
  `DateDispatch` date DEFAULT NULL COMMENT 'Срок отправки',
  `PeriodReview` date DEFAULT NULL COMMENT 'Срок рассмотрения',
  `Unknown` varchar(100) DEFAULT NULL,
  `CaseNum` char(10) DEFAULT NULL COMMENT 'Номер дела (страница, том, год)',
  `loadData` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=cp1251;
